trigger:
  - main
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run lint
    displayName: 'Run ESLint'

  - script: |
      npm run build
    displayName: 'Build Acorn Modules'

  - script: |
      npm test
    displayName: 'Run Tests'

  - task: CopyFiles@2
    inputs:
      contents: |
        acorn/dist/**
        acorn-loose/dist/**
        acorn-walk/dist/**
      targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
    displayName: 'Copy dist files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish dist as Artifact'
